"""Baseline schema for the self-contained personal Maverick-MCP database.

This squashes the previous migration history, which had become unusable after
the removal of the auth/billing/audit features (it referenced deleted
revisions such as ``002_add_authentication_tables``,
``012_remove_frontend_billing_system`` and ``add_stripe_webhook_events``). The
old files are preserved under ``alembic/versions/_archive_pre_baseline/`` for
reference.

The baseline creates the full current schema directly from the SQLAlchemy
model metadata (core models + every component model), so it always matches the
ORM. Future schema changes should be normal autogenerated migrations chained
from this revision.
"""

from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def _metadata():
    """Return the fully-populated model metadata (all components registered)."""
    import maverick_mcp.database.all_models  # noqa: F401 - registers all models
    from maverick_mcp.database.base import Base

    return Base.metadata


def upgrade() -> None:
    """Create every Maverick-MCP table. Idempotent via ``checkfirst``."""
    _metadata().create_all(bind=op.get_bind(), checkfirst=True)


def downgrade() -> None:
    """Drop every Maverick-MCP table."""
    _metadata().drop_all(bind=op.get_bind())
