"""add_brief_snapshots

Revision ID: 32f5bed6c959
Revises: 0001_baseline
Create Date: 2026-06-04 18:30:23.564875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f5bed6c959'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brief_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equity_value', sa.Float(), nullable=True),
    sa.Column('cash_balance', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('position_count', sa.Integer(), nullable=True),
    sa.Column('deployed_pct', sa.Float(), nullable=True),
    sa.Column('portfolio_conviction_score', sa.Float(), nullable=True),
    sa.Column('high_conviction_pct', sa.Float(), nullable=True),
    sa.Column('on_screen_pct', sa.Float(), nullable=True),
    sa.Column('off_screen_held_pct', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=50), nullable=True),
    sa.Column('regime_confidence', sa.Float(), nullable=True),
    sa.Column('synthesis', sa.Text(), nullable=True),
    sa.Column('positions_json', sa.JSON(), nullable=True),
    sa.Column('actions_json', sa.JSON(), nullable=True),
    sa.Column('screen_json', sa.JSON(), nullable=True),
    sa.Column('new_opportunities_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brief_snapshots_snapshot_at'), 'brief_snapshots', ['snapshot_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brief_snapshots_snapshot_at'), table_name='brief_snapshots')
    op.drop_table('brief_snapshots')
    # ### end Alembic commands ###