"""add_learned_weights

Revision ID: 679cf7481847
Revises: 85b470abb927
Create Date: 2026-06-17 08:12:30.228417

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '679cf7481847'
down_revision = '85b470abb927'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learned_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weights_json', sa.JSON(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('blend_factor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learned_weights_computed_at'), 'learned_weights', ['computed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learned_weights_computed_at'), table_name='learned_weights')
    op.drop_table('learned_weights')
    # ### end Alembic commands ###
