"""add_diversification_to_brief_snapshots

Revision ID: 7685ebfb7479
Revises: 32f5bed6c959
Create Date: 2026-06-16 17:36:52.722943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7685ebfb7479'
down_revision = '32f5bed6c959'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brief_snapshots', sa.Column('effective_bets', sa.Float(), nullable=True))
    op.add_column('brief_snapshots', sa.Column('diversification_grade', sa.String(length=2), nullable=True))
    op.add_column('brief_snapshots', sa.Column('largest_cluster_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brief_snapshots', 'largest_cluster_pct')
    op.drop_column('brief_snapshots', 'diversification_grade')
    op.drop_column('brief_snapshots', 'effective_bets')
    # ### end Alembic commands ###