"""add_position_snapshots

Revision ID: 85b470abb927
Revises: 7685ebfb7479
Create Date: 2026-06-16 17:57:35.580469

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '85b470abb927'
down_revision = '7685ebfb7479'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl_pct', sa.Float(), nullable=True),
    sa.Column('conviction_at_snapshot', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=50), nullable=True),
    sa.Column('position_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_snap_ticker_at', 'position_snapshots', ['ticker', 'snapshot_at'], unique=False)
    op.create_index(op.f('ix_position_snapshots_snapshot_at'), 'position_snapshots', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_position_snapshots_ticker'), 'position_snapshots', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_snapshots_ticker'), table_name='position_snapshots')
    op.drop_index(op.f('ix_position_snapshots_snapshot_at'), table_name='position_snapshots')
    op.drop_index('idx_pos_snap_ticker_at', table_name='position_snapshots')
    op.drop_table('position_snapshots')
    # ### end Alembic commands ###
